=== SparkleX/help-js/help-ui5/src/Order.xsd
<?xml version="1.0"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://localhost:8080"
	xmlns="http://localhost:8080"
	elementFormDefault="qualified">
	<!-- -->
	<xs:element name="OrderReports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Order" type="Order" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Order">
		<xs:sequence>
			<xs:element name="DocEntry" type="xs:int" />
			<xs:element name="CardCode" type="xs:string" />
			<xs:element name="DocTotal" type="xs:float" />
			<xs:element name="Detail" type="Detail" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Detail">
		<xs:sequence>
			<xs:element name="LineNum" type="xs:int" />
			<xs:element name="ItemCode" type="xs:string" />
			<xs:element name="LineTotal" type="xs:float" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== SparkleX/help-js/help-ui5/src/Order.xml
<OrderReports xmlns="http://localhost:8080" 
	targetNamespace="http://localhost:8080"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://localhost:8080 http://localhost:8080/Order.xsd"
	elementFormDefault="qualified">
	<Order>
		<DocEntry>100</DocEntry>
		<CardCode>C001</CardCode>
		<DocTotal>1.02</DocTotal>
		<Detail>
			<LineNum>1</LineNum>
			<ItemCode>I001</ItemCode>
			<LineTotal>100</LineTotal>
		</Detail>
		<Detail>
			<LineNum>2</LineNum>
			<ItemCode>I002</ItemCode>
			<LineTotal>200</LineTotal>
		</Detail>

	</Order>
	<Order>
		<DocEntry>101</DocEntry>
		<CardCode>C002</CardCode>
		<DocTotal>1.02</DocTotal>
		<Detail>
			<LineNum>1</LineNum>
			<ItemCode>I001</ItemCode>
			<LineTotal>100</LineTotal>
		</Detail>
		<Detail>
			<LineNum>2</LineNum>
			<ItemCode>I002</ItemCode>
			<LineTotal>200</LineTotal>
		</Detail>

	</Order>
</OrderReports>
